### ISSUE TITLE
Native JSR support?

### ISSUE THREAD

**Issue by XiNiHa** [nicolo-ribaudo/yarn-plugin-jsr#1]
It looks like [this plugin uses the npm compat layer](https://github.com/nicolo-ribaudo/yarn-plugin-jsr/blob/03a062a9927790450742693493519484d584e081/sources/jsr-protocol/Fetcher.ts#L52). Is it possible to directly use the JSR registry instead? Or is that a Yarn limitation?

**Comment by nicolo-ribaudo** [comment]
It is more of a limitation of pre-installing the dependencies (via an "install") command rather than resolving them at runtime, like Deno does.

Suppose there is a `@lodash/lodash` library with a bunch of entry-points (`./map`, `./reduce`, etc). In Deno, you would add `@lodash/lodash` to you `deno.json#imports` and then at runtime Deno sees that you are importing `@lodash/lodash/map` and downloads it.

Give that Yarn downloads file _before_ runtime execution, there is no way to know which imports you will use and thus it would still have to download all of them just in case. For this, using the JSR api directly doesn't give any benefit over just using the npm compat layer.
